"""Renamed name to username

Revision ID: 60c0cf9b1fd9
Revises: b324fc5dc56d
Create Date: 2025-07-28 20:53:12.978071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60c0cf9b1fd9'
down_revision = 'b324fc5dc56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_table('post')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('post_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_pkey'))
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('followers_followed_id_fkey')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('followers_follower_id_fkey')),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('followers_pkey'))
    )
    # ### end Alembic commands ###
