"""Rename table from user to users

Revision ID: a7163da23160
Revises: fc863d9b21a9
Create Date: 2025-07-03 03:55:24.055534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7163da23160'
down_revision = 'fc863d9b21a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('friends_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('friends_friend_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['friend_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('friends_friend_id_fkey'), 'user', ['friend_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('friends_user_id_fkey'), 'user', ['user_id'], ['id'])

    op.rename_table('users', 'user')
    # ### end Alembic commands ###
